### ISSUE TITLE
Plugin tries to resolve path relative to own directory

### ISSUE THREAD

**Issue by lxg** [caleb531/rollup-plugin-watch-globs#2]
For me, the plugin doesn’t work, and to be honest, I don’t know how it could work at all. (Maybe limited understanding of setups in which this has been tried.) 

In [index.ts#L14](https://github.com/caleb531/rollup-plugin-watch-globs/blob/main/index.ts#L14), the plugin tries to resolve the file location relative to its own directory (via the `__dirname` magic constant) but this can’t work when the plugin sits in the `node_modules` structure. Removing `__dirname` solved it for me.

**Comment by caleb531** [comment]
@lxg You know, you have an excellent point. I may have mistakingly written it like that because the `watchGlobs` function used to be part of my `rollup.config.js` (in which context, `__dirname` would make more sense).

But in the context of a Rollup plugin, yeah, `__dirname` doesn't make any sense at all unless there' was some quirk about the context in which Rollup plugins execute (but as you've shown, that not it).

Anyway, I'll have a bugfix release published today.

---

As a last note, I actually switched all my projects from Rollup to [Vite](https://vitejs.dev/), which not only eliminated my need for a plugin like this, but drastically simplified the boilerplate in my build pipeline. If your project complexity allows, I highly recommend it.

**Comment by caleb531** [comment]
@lxg Alright, I just published v2.0.1 with the fix. Hope it works better for you now:
https://www.npmjs.com/package/rollup-plugin-watch-globs

**Comment by lxg** [comment]
Thanks @caleb531, much appreciated!
